site_name: OCN - Oracle Cloud Native
site_url: https://ocn.dev.br
repo_url: https://github.com/daniel-armbrust/livro-ocn
site_description: Guia Prático para Implantação de Aplicações Cloud Native na Oracle Cloud Infrastructure (OCI).
site_author: Daniel Armbrust (darmbrust@gmail.com)
copyright: Copyright &copy; 2024 Daniel Armbrust. Todos os direitos reservados. 
lang: pt

theme:
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    - navigation.indexes
    - navigation.top
  name: material
  locale: pt_BR
  font:
    text: Open Sans
    code: Red Hat Mono
  palette:
  # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode      
      accent: deep orange
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: blue
      accent: deep purple    

markdown_extensions:
  - pymdownx.highlight:      
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true      
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details

extra_css:
  - css/extra.css
 
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/daniel-armbrust/

plugins:
  - minify:
      minify_html: true
      minify_css: true
      minify_js: true

nav:
  - Prefácio: ./prefacio.md
  - Sobre o Autor: ./sobre-o-autor.md
  - Como usar este Livro: ./como-usar-este-livro.md
  - Capítulo 1 - Introdução a Computação em Nuvem: ./capitulo-1/index.md
  - Capítulo 2 - OCI Foundations: ./capitulo-2/index.md
  - Capítulo 3 - Aplicação OCI PIZZA: ./capitulo-3/index.md
  - Capítulo 4 - Conectividade e Redes: ./capitulo-4/index.md
  - Capítulo 5 - Oracle NoSQL Database Cloud Service: ./capitulo-5/index.md
  - Capítulo 6 - Serviço de Computação: ./capitulo-6/index.md
  - Capítulo 7 - Desenvolvimento Moderno: ./capitulo-7/index.md
  - Capítulo 8 - Oracle Kubernetes Engine (OKE): ./capitulo-8/index.md
  - Capítulo 9 - Serviço DevOps: ./capitulo-9/index.md
  - Capítulo 10 - Monitoração e Observabilidade: ./capitulo-10/index.md
  - Capítulo 11 - Ferramental de IA: ./capitulo-11/index.md
  - Apêndice A - OCI HOWTOs: ./apendice-a/index.md
  - Bibliografia: ./bibliografia.md
  - ChangeLog: ./changelog.md