site_name: OCN - Oracle Cloud Native
site_url: https://ocn.dev.br
repo_url: https://github.com/daniel-armbrust/livro-ocn
site_description: Guia Prático para Implantação de Aplicações Cloud Native na Oracle Cloud Infrastructure (OCI).
site_author: Daniel Armbrust (darmbrust@gmail.com)
copyright: Copyright &copy; 2024 Daniel Armbrust. Todos os direitos reservados. 
lang: pt

theme:
  name: material
  locale: pt_BR
  font:
    text: Open Sans
    code: Red Hat Mono
  palette:
  # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode      
      accent: deep orange
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: blue
      accent: deep purple    

markdown_extensions:
  - pymdownx.highlight:      
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true      
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details

extra_css:
  - css/extra.css
 
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/daniel-armbrust/

plugins:
  - minify:
      minify_html: true
      minify_css: true
      minify_js: true
